edit path and their names

diff --git a/home/run_onchange_after_90-install-neovim.sh.tmpl b/home/run_onchange_after_90-install-neovim.sh.tmpl
--- a/home/run_onchange_after_90-install-neovim.sh.tmpl
+++ b/home/run_onchange_after_90-install-neovim.sh.tmpl
@@ -1,3 +1,5 @@
+{{- if .neovim.enable -}}
+{{- if eq .chezmoi.os "linux" -}}
 #!/bin/sh
 
 set -eu
@@ -5,32 +7,41 @@ set -eu
 # Get version from chezmoi data, environment, or ask interactively
 NVIM_VERSION="{{- .neovim.version | default "" -}}"
 PROFILE_FILE="{{ .profile | default "${HOME}/.profile" }}"
+
+LOCAL_PROGRAMS_DIR="{{ get . "programs_dir" | default ""  }}"
+LOCAL_PROGRAMS_DIR=${LOCAL_PROGRAMS_DIR:-${HOME}/.local}
+
+LOCAL_SOURCES_CODES="{{ get . "sources_codes" | default ""  }}"
+LOCAL_SOURCES_CODES=${LOCAL_SOURCES_CODES:-${HOME}/.sources_codes}
+
 NVIM_SOURCE_DIR="{{ get .neovim "source_codes" | default "" }}"
-NVIM_SOURCE_DIR="${NVIM_SOURCE_DIR:-${SOURCE_CODES:-${HOME}/.source_codes}/neovim}"
+NVIM_SOURCE_DIR="${NVIM_SOURCE_DIR:-${SOURCES_CODES:-${LOCAL_SOURCES_CODES}/neovim}"
 NVIM_PROGRAM_DIR="{{ get .neovim "program_dir" | default ""  }}"
-NVIM_PROGRAM_DIR="${NVIM_PROGRAM_DIR:-${PROGRAMS_DIR:-${HOME}/.local}/neovim}"
+NVIM_PROGRAM_DIR="${NVIM_PROGRAM_DIR:-${LOCAL_PROGRAMS_DIR}/neovim}"
+
+echo "Neovim source directory: ${NVIM_SOURCE_DIR}"
+echo "Neovim program directory: ${NVIM_PROGRAM_DIR}"
 
 # Skip reinstall if same version already installed
-
-if command -v NVIM_SOURCE_DIR/bin/nvim >/dev/null 2>$1; then
-    INSTALLED_VERSION="(NVIM_SOURCE_DIR/bin/nvim --version | head -n 1 | awk '{print $2}')"
+if command -v ${NVIM_PROGRAM_DIR}/bin/nvim >/dev/null 2>&1; then
+    INSTALLED_VERSION="(${NVIM_PROGRAM_DIR}/bin/nvim --version | head -n 1 | awk '{print \$2}')"; 
     if [ "${INSTALLED_VERSION}" = "${NVIM_VERSION}" ]; then
-        echo "Neovim $NVIM_VERSION already installed. Skipping."
+        echo "Neovim ${NVIM_VERSION} already installed. Skipping.";
         exit 0
     fi
 fi
 
 # Ask for version if not provided in environment
 
-if [ -z "$NVIM_VERSION" ]; then  
-    printf "Enter Neovim version (example: v0.10.4): "
-    read NVIM_VERSION
+if [ -z "${NVIM_VERSION}" ]; then  
+    printf "Enter Neovim version (example: v0.10.4): ";
+    read ${NVIM_VERSION};
 fi
 
 # Validate input
 
-if [-z "$NVIM_VERSION" ]; then
-    echo "Error version is required"
+if [-z "${NVIM_VERSION}" ]; then
+    echo "Error version is required";
     exit 1
 fi
 
@@ -40,25 +51,26 @@ REPO_URL="https://github.com/neovim/neovim.git"
 {{- include "install_packages/neovim/ubuntu_debian" -}}
     {{ end }}
 {{ else }}
-    echo "Unsupported OS: {{ .chezmoi.os }}"
-    exit 1
+    echo "Unsupported OS: {{ .chezmoi.os }}";
+    exit 1;
 {{ end }}
-echo "Install Neovim version: $NVIM_VERSION"
-neovim:
+echo "Install Neovim version: ${NVIM_VERSION}"
 
 # Remove old build directory
-rm  -rf "NVIM_SOURCE_DIR"
+rm  -rf ${NVIM_SOURCE_DIR}
 
 # Clone specific version
-git clone --branch "$NVIM_VERSION" --depth 1 "$REPO_URL" "$NVIM_SOURCE_DIR"
+git clone --branch "v${NVIM_VERSION}" --depth 1 "${REPO_URL}" "${NVIM_SOURCE_DIR}"
 
 cd $NVIM_SOURCE_DIR
 
 # Build dependencies and compile
-make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$NVIM_PROGRAM_DIR" CMAKE_BUILD_TYPE=Release
+make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=${NVIM_PROGRAM_DIR}" CMAKE_BUILD_TYPE=Release
 
 make install
 
-echo "Neovim $NVIM_VERSION installed successfully"
+echo "Neovim ${NVIM_VERSION} installed successfully"
 nvim --version | head -n 1
 
+{{- end }}
+{{- end }}
