edit neovim cloning command and remove ;

diff --git a/home/run_onchange_after_90-install-utilities.sh.tmpl b/home/run_onchange_after_90-install-utilities.sh.tmpl
--- a/home/run_onchange_after_90-install-utilities.sh.tmpl
+++ b/home/run_onchange_after_90-install-utilities.sh.tmpl
@@ -67,24 +67,24 @@ echo "Neovim version: v${NVIM_VERSION}"
 # Ask for version if not provided in environment
 
 if [ -z "${NVIM_VERSION}" ]; then  
-    printf "Enter Neovim version (example: v0.10.4): ";
-    read ${NVIM_VERSION};
+    printf "Enter Neovim version (example: v0.10.4): "
+    read ${NVIM_VERSION}
 fi
 
 # Validate input
 
 if [-z "${NVIM_VERSION}" ]; then
-    echo "Error version is required";
+    echo "Error version is required"
     exit 1
 fi
 
 # Skip reinstall if same version already installed
 if command -v ${NVIM_PROGRAM_DIR}/bin/nvim >/dev/null 2>&1; then
-    INSTALLED_VERSION="$(${NVIM_PROGRAM_DIR}/bin/nvim --version | head -n 1 | awk '{print $2}')"; 
+    INSTALLED_VERSION="$(${NVIM_PROGRAM_DIR}/bin/nvim --version | head -n 1 | awk '{print $2}')"
     echo "Installed neovim versiobn: ${INSTALLED_VERSION}"
     if [ "${INSTALLED_VERSION}" = "v${NVIM_VERSION}" ]; then
-        echo "Neovim v${NVIM_VERSION} already installed. Skipping.";
-        nvim --version | head -n 1
+        echo "Neovim v${NVIM_VERSION} already installed. Skipping."
+        ${NVIM_PROGRAM_DIR}/bin/nvim --version | head -n 1
         exit 0
     fi
 fi
@@ -96,8 +96,8 @@ REPO_URL="https://github.com/neovim/neovim.git"
 {{- include "install_packages/neovim/ubuntu_debian" -}}
 {{- end }}
 {{ else }}
-    echo "Unsupported OS: {{ .chezmoi.os }}";
-    exit 1;
+    echo "Unsupported OS: {{ .chezmoi.os }}"
+    exit 1
 {{ end }}
 echo "Install Neovim version: ${NVIM_VERSION}"
 
@@ -105,7 +105,7 @@ echo "Install Neovim version: ${NVIM_VERSION}"
 rm  -rf ${NVIM_SOURCE_DIR}
 
 # Clone specific version
-git clone --branch "${NVIM_VERSION}" --depth 1 "${REPO_URL}" "${NVIM_SOURCE_DIR}"
+git clone --branch "v${NVIM_VERSION}" --depth 1 "${REPO_URL}" "${NVIM_SOURCE_DIR}"
 
 cd $NVIM_SOURCE_DIR
 
@@ -115,7 +115,7 @@ make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=${NVIM_PROGRAM_DIR}" CMAKE_BUILD_
 make install
 
 echo "Neovim ${NVIM_VERSION} installed successfully"
-nvim --version | head -n 1
+${NVIM_PROGRAM_DIR}/bin/nvim --version | head -n 1
 {{- end }}
 
 {{- end }}
